version: "3.5"
services:
  postgres:
    container_name: postgres
    image: postgres
    #image: postgres:9.6
    networks:
      - localhost
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    #image: sonarqube:7.1
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - localhost
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on:
      - postgres

networks:
  localhost:
    name: localhost