apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostnames1
  name: hostnames1
spec:
  selector:
    app: hostnames1
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 9376