apiVersion: v1
kind: Pod
metadata:
  name: basic
  namespace: red
spec:
  containers:
    - name: ngnix-conteiner
      image: nginx:stable-alpine-perl
      restartPolicy: OnFailure
      ports:
      - containerPort: 80