apiVersion: v1
kind: Pod
metadata:
  name: basic
  namespace: red
spec:
  restartPolicy: OnFailure
  containers:
    - name: ngnix-conteiner
      image: nginx:stable-alpine-perl
      ports:
      - containerPort: 80