apiVersion: v1
kind: Service
metadata:
  name: cloudforce-svc
  namespace: ca1
spec:
  selector:
    app: cloudforce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32080
  type: NodePort
