apiVersion: v1
kind: Service
metadata:
  name: cloudacademy-svc
  namespace: red
spec:
  selector: 
    pod-name: basic
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: ClusterIP