apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"cloudacademy"},"name":"t2-svc","namespace":"skynet"},"spec":{"ports":[{"port":8080,"protocol":"TCP","targetPort":80}],"selector":{"app":"t3"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2024-02-14T04:53:47Z"
  labels:
    app: cloudacademy
  name: t2-svc
  namespace: skynet
  resourceVersion: "2877"
  uid: 3682ddd7-ed99-4d6a-baec-2619b7aa019e
spec:
  clusterIP: 10.105.106.114
  clusterIPs:
  - 10.105.106.114
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: t3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

  